---
root: true
plugins:
  - react
extends:
  - eslint:recommended
  - plugin:react/recommended
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  node: true
  browser: true
  es6: true
  jest: true
